[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/zdf7ms3g9jycpz7gw8dcwr8cqzlwi6fq-noctalia-shell-2026-02-04_eac8cf3/share/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/fumo/.cache/noctalia/placeholder.json"

